### ISSUE TITLE
undefined symbol: version_compare2

### ISSUE THREAD

**Issue by raz3k** [repology/postgresql-libversion#9]
Hello, 

I just installed postgresql-16 and compiled libversion using cmake and also compiled postgresql-libversion. Now when i try to create the extension in postgres I get: 
```
[postgres@nci-support-1 ~]$ psql --username postgres --dbname repology -c "CREATE EXTENSION libversion"
ERROR:  could not load library "/usr/pgsql-16/lib/libversion.so": /usr/pgsql-16/lib/libversion.so: undefined symbol: version_compare2
```

How to solve this ?

Thanks!

**Comment by AMDmi3** [comment]
Sorry, I do not offer any support in running Repology.
